[package]

name = "freetype-sys"
version = "0.16.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]
links = "freetype"
build = "build.rs"
keywords = ["freetype", "ffi"]
description = "Low level binding for FreeType font library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/freetype-sys.git"
homepage = "https://github.com/PistonDevelopers/freetype-sys"

[build-dependencies]
pkg-config = "0.3.11"
cmake = { version = "0.1.42", optional = true }

[dependencies]
libc = "0.2.42"

[features]
cmake = ["dep:cmake"]
